version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeuser -d financedb"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: ved06/project_backend:v1.0
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

  frontend:
    image: ved06/project_frontend:v1.0
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: